#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

import os
import sys
import json
import agent

request = json.load(sys.stdin)

agent.set_env("MINIO_HOST_SERVER", request['host_server'])
user = request.get('user', 'minioadmin')
password = request.get('password', 'minioadmin')
agent.set_env("MINIO_ROOT_USER", user)
agent.set_env("MINIO_ROOT_PASSWORD", password)
storage = request.get('storage', 'minio-data')
agent.set_env("MINIO_STORAGE", storage)

# Save configuration to JSON for later user and backup
with open('config.json', 'w') as config:
    config.write(json.dumps(request))
