#!/usr/bin/env python3

#
# Copyright (C) 2025 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

# Set TCP ports in the environment

import os
import agent

# split TCP ports and set them in the environment
server_port, console_port = os.environ['TCP_PORTS'].split(",")
agent.set_env("TCP_SERVER_PORT", server_port)
agent.set_env("TCP_CONSOLE_PORT", console_port)
