#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

import json
import sys
import agent
import os

config = {'user': 'minioadmin', 'password': 'minioadmin', 'host_server' : '', 'host_console': '', 'lets_encrypte': False}

try:
    # Read current configuration from config file
    with open('config.json', 'r') as cf:
        config = json.loads(cf.read())
        config['lets_encrypt'] = (
            agent.get_route(f"{os.environ['MODULE_ID']}-console").get('lets_encrypt', False) and
            agent.get_route(f"{os.environ['MODULE_ID']}-server").get('lets_encrypt', False)
        )
except:
    pass

json.dump(config, fp=sys.stdout)
