#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

import os
import sys
import json
import agent
import agent.tasks

config = {}

# Read current configuration from config file
with open('config.json', 'r') as cf:
    config = json.loads(cf.read())

server_port, console_port = os.environ['TCP_PORTS'].split(",")
agent.set_env("TCP_SERVER_PORT", server_port)
agent.set_env("TCP_CONSOLE_PORT", console_port)

agent.set_env("MINIO_HOST_SERVER", config['host_server'])
user = config.get('user', 'minioadmin')
password = config.get('password', 'minioadmin')
agent.set_env("MINIO_ROOT_USER", user)
agent.set_env("MINIO_ROOT_PASSWORD", password)

# Make sure everything is saved inside the environment file
# just before starting systemd unit
agent.dump_env()
